import { ExistingCharacters } from './Characters'

export const Quotes: Record<ExistingCharacters, string[]> = {
  jon: [
    'The man who passes the sentence should swing the sword.',
    'The North remembers.',
    'Winter is coming.',
    "I don't want it.",
    'I am the sword in the darkness. I am the watcher on the walls. I am the shield that guards the realms of men.',
    "I'm not a Stark.",
    "I've never been with a woman. Or a man.",
    'I did what I thought was right, and I got murdered for it.',
    "The Night's Watch is my family now.",
    "I'm tired of fighting.",
    "I'm not a leader.",
    "I don't know how to do that. I thought I did, but I failed.",
    "The wildlings can't march on an empty stomach.",
    'I will never sit on the Iron Throne.',
    'If you have to say you are a king, then you are no king.',
    "I don't want anyone following me.",
    'The things I do for love.',
    "I'm not afraid of death. I've done it already.",
    'Sometimes, a person has to choose.',
    "I'm not asking you to forget your dead. I'll never forget mine.",
    "I don't know how to pretend.",
    "We're all just songs in the end. If we're lucky.",
    "I've grown used to him.",
    "I'm not your brother.",
    "I'm not going to swear an oath I can't uphold.",
    "I've never been much of a fighter.",
    "I didn't know Ser Alliser's first name was 'F***.'",
    "I didn't have much say in that.",
    "I'm not a God.",
    'I want to fight for the side that fights for the living.',
    'I have to go home now.',
    'The Long Night is coming, and the dead come with it.',
    "I've never been a Stark.",
    'I wish you good fortune in the wars to come.',
    "I've seen what I can do. I've seen the future.",
    'I never wanted a crown.',
    "I don't know how to lead.",
    "I'm not a lord.",
    "I don't want anyone following me. I don't want anyone dying for me.",
    "I don't want anyone's blood on my hands.",
    "I'm tired of fighting.",
    "We're here to say goodbye to our brothers and sisters. To our fathers and mothers. To our friends. Our fellow men and women who set aside their differences to fight together and die together so that others might live.",
    "I will not punish a son for his father's sins, and I will not take a family home away from a family it has belonged to for centuries.",
    'The king in the north!',
    "I'm not a hero.",
    "I don't deserve this.",
    "They can't respect you if you're wearing a dress.",
    "We're not children anymore.",
    "I've made my choice.",
    "I'm not going to stop the wheel. I'm going to break the wheel.",
    "I'm not going to swear an oath I can't uphold.",
    "I'm tired of fighting.",
    'We are the watchers on the wall.',
    "I'm sorry I never came to say goodbye.",
    "I don't want anyone following me.",
    "We'll go back to the way it was."
  ],
  ned: [
    'The man who passes the sentence should swing the sword.',
    'Winter is coming.',
    'The lone wolf dies, but the pack survives.',
    'The only time a man can be brave is when he is afraid.',
    'The man who fears losing has already lost.',
    'The man who never reads lives only one.',
    'A ruler who hides behind paid executioners soon forgets what death is.',
    'I, Eddard, the House Stark, Lord of Winterfell, and Warden of the North, sentence you to die.',
    'The past remains the past. We can learn from it, but we cannot change it.',
    'The only time a man can be brave is when he is afraid.',
    'The Starks are always right eventually. Winter is coming!',
    "He won't be a boy forever. And winter is coming.",
    'A lord must learn that sometimes words can accomplish what swords cannot.',
    'The man who passes the sentence should swing the sword.',
    "I'm not a Stark.",
    'When the snows fall and the white winds blow, the lone wolf dies, but the pack survives.',
    "If you would take a man's life, you owe it to him to look into his eyes and hear his final words. And if you cannot bear to do that, then perhaps the man does not deserve to die.",
    'You think my life is such a precious thing to me, that I would trade my honor for a few more years... of what?',
    'A true man does what he will, not what he must.',
    'You think my life is some precious thing to me? That I would trade my honor for a few more years? You grew up with actors. You learned their craft and you learnt it well. But I grew up with soldiers. I learned to die a long time ago.',
    "I don't fight in tournaments because when I fight a man for real, I don't want him to know what I can do.",
    'The Targaryens wed brothers and sisters for 300 years to keep the bloodline pure. Jaime and I are more than brother and sister. We shared a womb. We came into this world together, we belong together.',
    'I promise you, I will go to the king and I will ask him to let you go back to the Wall. I swear it.',
    'When you play the game of thrones, you win or you die.',
    "The wolf and the lion will be at each other's throats. We will be at war soon, my friend.",
    'We find our true friends on the battlefield.',
    "The next time we see each other, we'll talk about your mother. I promise.",
    'A lion does not concern himself with the opinion of sheep.',
    'A man can only be brave when he is afraid.',
    'If you lose, you will be killed. If you win, you will be executed as a traitor.',
    'The day will come when you think you are safe and happy, and your joy will turn to ashes in your mouth.',
    'I have no choice but to refuse you.',
    'A mind needs books as a sword needs a whetstone if it is to keep its edge.',
    'The more people you love, the weaker you are. Love no one but your children.',
    'The man who passes the sentence should swing the sword.',
    'You think my life is such a precious thing to me, that I would trade my honor for a few more years... of what?',
    'I did not fight beside you on the field and I will regret that until my dying day. A man can only admit when he was wrong and ask forgiveness.',
    'I did not want that woman within a hundred miles of our boys.',
    'The winters are hard, but the Starks will endure. We always have.',
    "I was never so alive as when I was winning this throne, or so dead as now that I've won it.",
    'The man who passes the sentence should swing the sword.',
    'Our way is the old way.',
    'I plan to head north, I plan to find our men, then I plan to free them.',
    'War was easier than daughters.',
    'The only time a man can be brave is when he is afraid.',
    'The direwolf is the sigil of your House. They were meant to have them.',
    "I don't fight in tournaments because when I fight a man for real, I don't want him to know what I can do.",
    "We are not going to die. - Just once, I would like to know what it's like to play without my life at stake.",
    'No, now it ends.',
    "I'm not a Stark.",
    'The Targaryens wed brothers and sisters for 300 years to keep the bloodline pure. Jaime and I are more than brother and sister. We shared a womb. We came into this world together, we belong together.',
    'I promise you, I will go to the king and I will ask him to let you go back to the Wall. I swear it.'
  ],
  sansa: [
    "I am Sansa Stark of Winterfell. This is my home, and you can't frighten me.",
    'I did what I had to do to survive, my lady. But I am a Stark, I will always be a Stark.',
    "Arya, we're family. The four of us. The last of the Starks.",
    "I've known him my whole life. He's nothing like that.",
    "I'm a slow learner, it's true. But I learn.",
    "I don't know how to be Lord of anything. I hardly know how to use a fork.",
    'The past is the past. The North is the future.',
    "I'm not a child. I'm the Lady of Winterfell, and I'm home.",
    "I'm not what I want to be. Not yet.",
    'The most heroic thing we can do now is look the truth in the face.',
    "I'm not like my mother. I'm not like my father. I am Sansa Stark of Winterfell. This is my home, and you can't frighten me.",
    'The North is as beautiful as your brother claimed. As are you.',
    "I will never set foot in King's Landing again.",
    "You're the Lady of Winterfell. The King in the North chose you to rule in his absence. And rule you have.",
    "The smartest person I've ever met... is you.",
    'I have to go home now.',
    "I'll never forget what you did. I can never repay you.",
    'I have so many names now, I can hardly keep them straight.',
    'The lone wolf dies, but the pack survives.',
    'The most beautiful woman in the world has come to take my place.',
    'I did what I had to do to survive.',
    "I'm not the one who's running, Ser Gregor. I'm not the one hiding.",
    "I'm not a little bird anymore.",
    'Jon needs to know the truth.',
    "I don't know how to play.",
    'I thought Arya was dead.',
    'You freed me from the monsters who murdered my family, and you gave me to other monsters who murdered my family.',
    "A girl is Arya Stark of Winterfell. And I'm going home.",
    'Winterfell is yours, Your Grace.',
    'The North will remain an independent kingdom, as it was for thousands of years.',
    'I did what I had to do to survive, my lady. But I am a Stark, I will always be a Stark.',
    "I'm Sansa Stark of Winterfell. This is my home, and you can't frighten me.",
    'A true leader avails himself of the wisest counsel he can find.',
    'I never should have left Winterfell.',
    'When the snows fall and the white winds blow, the lone wolf dies, but the pack survives.',
    'I have so many names, now. Lady Stark, the Widow, the Mother of the North. But I wish I could be who I was before.',
    "I'm not a lady.",
    "He's a monster, you do know that.",
    'I have to go home now.',
    "I don't want someone brave and gentle and strong. I want him.",
    "Sometimes when I try to understand a person's motives, I play a little game. I assume the worst.",
    "I'll never forget what you did. I can never repay you.",
    "I'm not the one who's running, Ser Gregor. I'm not the one hiding.",
    "I'm not a little bird anymore.",
    'I thought Arya was dead.',
    'I have so many names now, I can hardly keep them straight.',
    'The lone wolf dies, but the pack survives.',
    'I did what I had to do to survive.',
    "I don't know how to play.",
    'Jon needs to know the truth.',
    'You freed me from the monsters who murdered my family, and you gave me to other monsters who murdered my family.'
  ],
  arya: [
    'The man who passes the sentence should swing the sword.',
    "A girl is Arya Stark of Winterfell. And I'm going home.",
    'A girl is no one.',
    'The North remembers.',
    'Not today.',
    'The night is dark and full of terrors.',
    'When the snows fall and the white winds blow, the lone wolf dies, but the pack survives.',
    'I am not a lady.',
    'Leave one wolf alive, and the sheep are never safe.',
    "Nothing isn't better or worse than anything. Nothing is just nothing.",
    'The First Sword of Braavos does not run.',
    'I can be your family.',
    "I'm not a wolf, but I'm not a lion, either.",
    'Fear cuts deeper than swords.',
    "I'm not going to stop the wheel. I'm going to break the wheel.",
    'The pack survives.',
    "That's not you.",
    'Death has many faces. I look forward to seeing this one.',
    "The only one thing we say to death is 'not today.'",
    'A bruise is a lesson... and each lesson makes us better.',
    'Every hurt is a lesson, and every lesson makes you better.',
    "Someday, I'm going to put a sword through your eye and out the back of your skull.",
    "I can't sleep until I say the names.",
    'You know who you sound like? A bloody woman.',
    "The world doesn't just let girls decide what they're going to be.",
    'When people ask you what happened here, tell them the North remembers. Tell them winter came for House Frey.',
    "I don't need help to protect my family.",
    "My name is Arya Stark. I want you to know that. The last thing you're ever going to see is a Stark smiling down at you as you die.",
    "That's not the monster I was talking about. I'm looking for someone.",
    "I don't plan on knitting by the fire while men fight for me.",
    'Not my hair, Ned loves my hair.',
    "I'm not a lady, I never have been. That's not me.",
    "The world is built by killers... so you'd better get used to looking at them.",
    "A girl is Arya Stark of Winterfell, and I'm going home.",
    "I'm done with this. I want you to know that the last thing you're ever going to see is a Stark smiling down at you as you die.",
    "We're going to die if we stay here.",
    "Nothing isn't better or worse than anything. Nothing is just nothing.",
    "I can't remember what she looked like. I only know she was the one thing I ever wanted... someone took her away from me, and seven kingdoms couldn't fill the hole she left behind.",
    "I don't want to be a lady.",
    'The North remembers.',
    'The man who passes the sentence should swing the sword.',
    'The night is dark and full of terrors.',
    'When the snows fall and the white winds blow, the lone wolf dies, but the pack survives.',
    'I am not a lady.',
    'Leave one wolf alive, and the sheep are never safe.',
    'Fear cuts deeper than swords.',
    "I'm not going to stop the wheel. I'm going to break the wheel.",
    "That's not you.",
    'Death has many faces. I look forward to seeing this one.',
    "The only one thing we say to death is 'not today.'",
    'Every hurt is a lesson, and every lesson makes you better.',
    "Someday, I'm going to put a sword through your eye and out the back of your skull.",
    "I can't sleep until I say the names.",
    'You know who you sound like? A bloody woman.',
    "The world doesn't just let girls decide what they're going to be.",
    'When people ask you what happened here, tell them the North remembers. Tell them winter came for House Frey.',
    "I don't need help to protect my family.",
    "My name is Arya Stark. I want you to know that. The last thing you're ever going to see is a Stark smiling down at you as you die.",
    "I don't plan on knitting by the fire while men fight for me.",
    'Not my hair, Ned loves my hair.',
    "I'm not a lady, I never have been. That's not me.",
    "The world is built by killers... so you'd better get used to looking at them."
  ],
  catelyn: [
    'Family, duty, honor.',
    'Show them how it feels to lose what they love.',
    'A mother has no choice but to protect her children.',
    "I am a Stark of Winterfell. This is my home, and you can't frighten me.",
    'I will not have you without honor.',
    'The things I do for love.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'When you play the game of thrones, you win or you die.',
    'Winter is coming.',
    "It's the family name that lives on. It's all that lives on."
  ],
  jaime: [
    'The things I do for love.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'By what right does the wolf judge the lion?',
    'Kingslayer, Oathbreaker, Man without honor. What do you call a knight who has forsaken every vow he ever swore?',
    "We don't get to choose who we love.",
    "The world isn't fair. Never has been, never will be.",
    "I'm not the honorable Ned Stark. I wouldn't have trusted me, either.",
    'There are no men like me, only me.',
    'When you play the game of thrones, you win or you die.',
    'Tell me, if your precious Renly commanded you to kill your own father and stand by while thousands of men, women, and children burned alive, would you have done it? Would you have kept your oath then?',
    'I learned from Ser Arthur Dayne, the Sword of the Morning, who could have slain all five of you with his left hand while he was taking a piss with the right.',
    "The things I do for love. It wasn't worth it.",
    "It's the family name that lives on. It's all that lives on.",
    "The more you give a king, the more he wants. We are only human. Oh, wait. No, we're not.",
    "The knights of the Kingsguard are forbidden to marry. I can sing and dance, but I can't marry.",
    "It's all fallen on me.",
    "I'll hear no more of this. I am your king.",
    'The king shits, and the Hand wipes.',
    'The king is tired. See him to his chambers.',
    "Aerys saw traitors everywhere. So he had their tongues torn out, any man with a loud voice who didn't keep mum. And these were the small sins. The great ones... well, you can imagine.",
    'There are no men like me. Only me.',
    "So many vows... they make you swear and swear. Defend the king. Obey the king. Keep his secrets. Do his bidding. Your life for his. But obey your father. Love your sister. Protect the innocent. Defend the weak. Respect the gods. Obey the laws. It's too much. No matter what you do, you're forsaking one vow or the other.",
    "I love her. And I love my brother, and I love the king. But we are all human. Oh, wait. No, we're not.",
    "The things I do for love... it's a beautiful dream, stopping the wheel. You're not the first person who's ever dreamt it.",
    "Fools. As if I'm not deep enough in this already.",
    'The High Sparrow rules this city, and the Faith Militant. When you attack the Faith, you attack the city.',
    'Power is power.',
    "There's only one war that matters. The Great War. And it is here.",
    'The last thing I want is to feel responsible for you.',
    "I was a little worse for wear. Stannis' best. Nothing to write home about."
  ],
  tyrion: [
    'I have a tender spot in my heart for cripples, bastards, and broken things.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'I drink and I know things.',
    "It's not easy being drunk all the time. Everyone would do it if it were easy.",
    "I'm not questioning your honor, Lord Janos. I'm denying its existence.",
    'Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.',
    "I try to know as many people as I can. You never know which one you'll need.",
    "I'm guilty of being a dwarf. I've been on trial for that my entire life.",
    "The world isn't fair, and no matter how good and just you try to be, you can't make it that way.",
    "Oh, I'm a monster. Perhaps you should speak to me more softly, then. Monsters are dangerous, and just now kings are dying like flies.",
    "That's what I do: I drink, and I know things.",
    "When you tear out a man's tongue, you are not proving him a liar. You're only telling the world that you fear what he might say.",
    "The powerful have always preyed on the powerless. That's how they became powerful in the first place.",
    "Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?",
    "If you're going to be a cripple, it's better to be a rich cripple.",
    "Chaos isn't a pit. Chaos is a ladder.",
    'When you play the game of thrones, you win or you die.',
    'I am not questioning your honor, I am denying its existence.',
    "It's not easy being drunk all the time. Everyone would do it if it were easy.",
    "Let them see that their words can cut you, and you'll never be free of the mockery. If they want to give you a name, take it, make it your own. Then they can't hurt you with it anymore.",
    'My mind is my weapon. My brother has his sword, King Robert has his warhammer, and I have my mind... and a mind needs books as a sword needs a whetstone if it is to keep its edge.',
    'I would rather be the right hand of the devil than in his path.',
    'Death is so final, yet life is full of possibilities.',
    "It's a shame the throne isn't made of cocks. They'd have never got him off it.",
    'The greatest fools are ofttimes more clever than the men who laugh at them.',
    "I'm quite good at spending money, but a lifetime of outrageous wealth hasn't taught me much about managing it.",
    "The gods have no mercy, that's why they're gods.",
    'A mind needs books as a sword needs a whetstone, if it is to keep its edge.',
    "A day will come when you think you are safe and happy, and your joy will turn to ashes in your mouth, and you'll know the debt is paid.",
    'A lion does not concern himself with the opinion of sheep.'
  ],
  cersei: [
    'When you play the game of thrones, you win or you die.',

    'Power is power.',

    "Tears aren't a woman's only weapon. The best one's between your legs.",

    "Everyone who isn't us is an enemy.",

    'The more people you love, the weaker you are.',

    "A lion doesn't concern itself with the opinion of sheep.",

    'Gold will be their crowns, gold their shrouds.',

    "I will do things for my family you couldn't imagine.",

    "You love your children. It's your one redeeming quality. That and your cheekbones.",

    'I should wear the armor and you the gown.',

    "I'm a lioness. I will not cringe for them.",

    'The High Sparrow is a dangerous man.',

    "I'm a lion in a field of sheep.",

    "It's the family name that lives on. It's all that lives on.",

    'In the game of thrones, you win or you die. There is no middle ground.',

    'The things I do for love.',

    'I choose violence.',

    'A good king knows when to save his strength and when to destroy his enemies.',

    "I will not become a page in someone else's history book.",

    'I will burn their cities to the ground if they touch her.',

    'A true man does what he will, not what he must.',

    'I am a lioness. I will not be caged.',

    "The past is the past, the future is all that's worth discussing.",

    'I will burn our house to the ground before I let that happen.',

    'I will do whatever I need to do.',

    'I will do whatever I have to do.',

    'I would burn cities to the ground. You are all that matters.',

    'You should never believe a thing simply because you want to believe it.',

    'The only way to keep your people loyal is to make certain they fear you more than they do the enemy.',

    "The realm. Do you know what the realm is? It's the thousand blades of Aegon's enemies, a story we agree to tell each other over and over until we forget that it's a lie."
  ],
  baelish: [
    "Chaos isn't a pit. Chaos is a ladder.",
    'I did warn you not to trust me.',
    "Don't fight in the North or the South. Fight every battle, everywhere, always, in your mind.",
    'The climb is all there is.',
    'A man with no motive is a man no one suspects. Always keep your foes confused.',
    'Knowledge is power.',
    'I have only loved one woman, only one, my entire life. Your sister.',
    "A lion doesn't concern itself with the opinion of sheep.",
    "I'm not going to fight them. I'm going to [expletive] them.",
    'Gold wins wars, not soldiers.',
    "Money buys a man's silence for a time, a bolt in the heart buys it forever.",
    'Influence grows like a weed. I tend to it.',
    "The realm. Do you know what the realm is? It's the thousand blades of Aegon's enemies, a story we agree to tell each other over and over until we forget that it's a lie.",
    'The things I do for love.',
    "Do you know what the realm is? It's the thousand blades of Aegon's enemies, a story we agree to tell each other over and over until we forget that it's a lie.",
    "Every time I'm faced with a decision, I close my eyes and see the same picture. Whenever I consider an action, I ask myself, 'Will this action help to make this picture a reality?' Pull it out of my mind and into the world, and I only act if the answer is yes.",
    "Always keep your foes confused. If they don't know who you are or what you want, they can't know what you plan to do next.",
    "A man's got to have a code.",
    "You know what I learnt losing that duel? I learnt that I'll never win. Not that way. That's their game, their rules. I'm not going to fight them. I'm going to [expletive] them.",
    'A man with no motive is a man no one suspects. Always keep your foes confused.',
    "I'm not going to fight them. I'm going to [expletive] them.",
    'Gold wins wars, not soldiers.',
    "Money buys a man's silence for a time, a bolt in the heart buys it forever.",
    'Influence grows like a weed. I tend to it.',
    "I'm not going to fight them. I'm going to [expletive] them.",
    'A man with no motive is a man no one suspects. Always keep your foes confused.',
    'I have only loved one woman, only one, my entire life. Your sister.',
    'Influence grows like a weed. I tend to it.',
    "The realm. Do you know what the realm is? It's the thousand blades of Aegon's enemies, a story we agree to tell each other over and over until we forget that it's a lie.",
    "Money buys a man's silence for a time, a bolt in the heart buys it forever."
  ],
  bran: [
    "I'm not a Stark.",
    'I saw you at the crossroads.',
    "Chaos isn't a pit. Chaos is a ladder.",
    "I can't be Lord of Winterfell. I can never be Lord of anything.",
    "I'm not even a lord, just a bastard.",
    "I'm not a cripple.",
    "I didn't want anyone to die for me.",
    'I can never be a knight.',
    "I'm the three-eyed raven now.",
    'I see everything.',
    'You were right the whole time.',
    "I can't have children.",
    'We need to be ready.',
    'I have to go.',
    'The Night King is coming.',
    'The past is already written. The ink is dry.',
    "The world's not just black and white.",
    "I can't remember everything.",
    "I can't stay here.",
    "I'm not who I used to be.",
    'I have to learn to see better.',
    'We have to be ready for this.',
    'I have to find the Three-Eyed Raven.',
    "I'm not a Stark anymore.",
    "I'm something else now.",
    "It's beautiful beneath the sea, but stay too long and you'll drown.",
    "I don't want to be anyone.",
    'I remember everything.',
    'I have to go now. Goodbye.'
  ],
  daenerys: [
    'I am the blood of the dragon.',
    'I will take what is mine with fire and blood.',
    'I am the Mother of Dragons.',
    'I am not a queen, I am a Khaleesi.',
    'Dracarys.',
    'I will answer injustice with justice.',
    'I will break the wheel.',
    "I'm not going to stop the wheel. I'm going to break the wheel.",
    'I am not a princess. I am a Khaleesi.',
    'I am the last Targaryen.',
    "I'm not going to sail for Westeros. I'm going to sail for the Seven Kingdoms.",
    'The next time you raise a hand to me will be the last time you have hands.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'I will do what queens do.',
    'I was born to rule the Seven Kingdoms.',
    'Valar Morghulis.',
    'Dracarys, Dracarys!',
    'The Dothraki follow strength above all.',
    'I will make the world a better place.',
    "I'm not going to stop the wheel. I'm going to break the wheel.",
    'I will take what is mine with fire and blood.',
    'I will answer injustice with justice.',
    'A Targaryen alone in the world is a terrible thing.',
    'The people of Meereen are free.',
    "I'm not a politician; I'm a queen.",
    'I am not your little princess.',
    'I am no ordinary woman.',
    'The Unsullied are not men; they do not rape.',
    "I'm not going to sail for Westeros. I'm going to sail for the Seven Kingdoms.",
    'I am the Mother of Dragons, and I swear to you that those who would harm you will die screaming.'
  ],
  joffrey: [
    'I am the king!',
    'My father won the real war. He killed Prince Rhaegar. He took the crown while you hid under Casterly Rock!',
    'They should be loyal to me.',
    "I'm the king. I can do as I like.",
    "I'll have his head on a spike.",
    'Bow before your king!',
    "I'll have a pretty red smile from ear to ear.",
    "What is it you're saying?",
    "If I tell the Hound to cut you in half, he'll do it without a second thought.",
    "They say Stannis never smiles. I'll give him a red smile from ear to ear.",
    "I'm the king. I'll have the other two.",
    "There's a new one every day. But you get used to them.",
    'The king can do as he likes!',
    'I am the king, and I will punish you.',
    'Kill them. Kill them all.',
    "This is the kind of [expletive] you and the other noble ladies enjoy, isn't it? I know he did, that little rat.",
    "I won't have my son dressed as a whore.",
    "I don't care what you swore!",
    "I'll have a song from my new blade. If I'm not the king, then who is?",
    'I want to see him [Ned Stark] die.',
    'The king can do as he likes!',
    "They say Stannis never smiles. I'll give him a red smile from ear to ear.",
    'I am the king. I can do as I like.',
    "I'll have a pretty red smile from ear to ear.",
    "I'm not trying to honor you. I'm trying to get you to run my kingdom while I eat, drink, and whore my way to an early grave.",
    "If I tell the Hound to cut you in half, he'll do it without a second thought.",
    "I'm the king. I'll have the other two.",
    "There's a new one every day. But you get used to them.",
    'The king can do as he likes.'
  ],
  melisandre: [
    'The night is dark and full of terrors.',
    'The Lord of Light will watch over us.',
    'For the night is dark and full of terrors.',
    'The night is dark, and the cold is coming.',
    'I have seen your victory in the flames.',
    'There is only one war that matters. The Great War.',
    'The Lord of Light has shown me your purpose.',
    'The darkness is coming for us all.',
    'The night is long and full of terrors.',
    'The Lord of Light guides us.',
    'You are the prince that was promised.',
    "The Lord of Light's fire burns within me.",
    'The Lord of Light has made you powerful.',
    'I see a darkness in you.',
    'The night is dark, and full of terrors.',
    'I serve the Lord of Light.',
    'The Lord of Light will show us the way.',
    'The night is dark, but we have the light.',
    'The Lord of Light demands a sacrifice.',
    'I have seen your destiny, and it is glorious.',
    'You are the chosen one.',
    'I am a servant of the Lord of Light.',
    'The night is dark, but the dawn is coming.',
    "The Lord of Light's power is within me.",
    'The night is long and full of terrors.',
    'The Lord of Light has blessed you with his favor.',
    "The darkness is a part of the Lord's plan.",
    'The Lord of Light will protect us.',
    'I have looked into the flames and seen the future.',
    'The night is dark, but the fire burns within us.'
  ],
  olenna: [
    'I was good. I was very, very good.',
    'War is war, but killing a man at a wedding? Horrid. What sort of monster would do such a thing?',
    "You don't think I'd let you marry that beast, do you?",
    'You love her. You really do love her. You poor fool.',
    'All I could think about was how much I wanted to be away from her.',
    "Margaery is the queen. You are not the queen because you're not married to the king. I do appreciate these things can get a bit confusing in your family.",
    "You don't think I'd let you marry that beast, do you?",
    "I'm the queen of thorns.",
    "I'd hate to die like your son. Clawing at my neck, foam and bile spilling from my mouth, eyes blood red, skin purple. Must have been horrible for you, as a Kingsguard, as a father. It was horrible enough for me.",
    "I wonder if you're the worst person I've ever met. At a certain age, it's hard to recall. But the truly vile do stand out through the years.",
    'A girl is far too young to be a widow. And I am far too old to marry the king. But seem to be the royal person at this particular moment. So here we are.',
    'What happens when the nonexistent bumps against the decrepit?',
    "It's a rare-enough thing. A man who lives up to his reputation.",
    'As for your veiled threats... I must confess, I do not have any idea what you mean.',
    'Wars are rather good for the purse.',
    'That House [House Tyrell] is the future of our house, the future of our family.',
    "Better to gamble on the man you know than the strangers you don't. And you thought I was a gambler.",
    'My reign is really just beginning.',
    'I was good. I was very, very good.',
    'War is war, but killing a man at a wedding? Horrid. What sort of monster would do such a thing?',
    'You love her. You really do love her. You poor fool.',
    'All I could think about was how much I wanted to be away from her.',
    "Margaery is the queen. You are not the queen because you're not married to the king. I do appreciate these things can get a bit confusing in your family.",
    "You don't think I'd let you marry that beast, do you?",
    "I'm the queen of thorns.",
    "I'd hate to die like your son. Clawing at my neck, foam and bile spilling from my mouth, eyes blood red, skin purple. Must have been horrible for you, as a Kingsguard, as a father. It was horrible enough for me.",
    "I wonder if you're the worst person I've ever met. At a certain age, it's hard to recall. But the truly vile do stand out through the years.",
    'A girl is far too young to be a widow. And I am far too old to marry the king. But seem to be the royal person at this particular moment. So here we are.',
    'What happens when the nonexistent bumps against the decrepit?',
    "It's a rare-enough thing. A man who lives up to his reputation."
  ],
  samwell: [
    "I can't steal her. She's a person, not a goat.",
    'I am not what you think I am.',
    'Sometimes a man has to make hard choices, choices that might look wrong to others, but you know are right in the long run.',
    "I'm not as good as you at this sort of thing.",
    "It's not easy being me.",
    'The things I do for love.',
    'I always wanted to be a wizard.',
    "I thought the Night's Watch might make a man out of me.",
    'I read about it in a book.',
    "I'm not a fighter.",
    "It's a tough decision. We've got to make it.",
    "I'm not a hero. I'm a high-functioning coward.",
    "I'm a coward. I'm not a brave man.",
    "I know it's not what I'm supposed to be doing, but I'm not really cut out for this sort of thing.",
    'We need to be ready.',
    "I've always been weak.",
    'I just wish I was the man that she deserves.',
    'I just want to go home.',
    "I'm not as smart as you. I can't help you like you want.",
    "I'm not a fighter, but I'm not going to stand by and watch people get hurt.",
    'I just want to be a part of something, to belong.',
    "I don't want to die. I'm sorry, but I don't want to die.",
    'I just want to protect Gilly and the baby.',
    "I thought I'd be a coward for the rest of my life.",
    "I'm not the bravest man, but I'll do what I can.",
    "I'm not as brave as Jon.",
    "I've seen things that I can't explain.",
    'I just want to make a difference.',
    'I never knew my mother. Gilly was the closest thing to a mother that little Sam will ever have.',
    "I can't steal her. She's a person, not a goat."
  ],
  theon: [
    "I'm a Greyjoy of Pyke, and we do not sow.",
    'I am a lord, and I will be addressed as such.',
    "My real father lost his head at King's Landing.",
    "I'm not a Stark, I'm a Greyjoy.",
    'I will not have my honor questioned by an imp.',
    'My loyalty is to my family and my house.',
    'You have to know your name.',
    'I have to be cruel for a little while, or the Iron Islands will never respect me.',
    "I've lived with him, hunted with him, and you are one of his bannermen.",
    'Every night, I wake up in a cold sweat.',
    'Reek, my name is Reek.',
    'The Stark boys are gone.',
    "You can't kill me. I'm part of you now.",
    'I was taken from my home, from my family.',
    'I want to be a great lord, like my father.',
    'I want to prove myself to my father.',
    'No one can save me. No one can save anyone.',
    'I should have never left the Iron Islands.',
    'I was a fool for trusting in the Starks.',
    'I was raised at Winterfell, but I am not a Stark.',
    'I had to do what I had to do to survive.',
    "I'm a prisoner in my own mind.",
    'I can never go back home.',
    "I've done terrible things, and I can never make amends.",
    'I betrayed my own blood.',
    "I've become a different person.",
    'I was a hostage, but I lost myself.',
    "I've paid the iron price for my mistakes.",
    "I'm haunted by my past.",
    "I'm not the man I once was."
  ],
  tywin: [
    "A lion doesn't concern itself with the opinion of sheep.",
    'The house that puts family first will always defeat the house that puts the whims and wishes of its sons and daughters first.',
    'A lion must not concern itself with the opinion of sheep.',
    'Some wars are won with swords and spears, others with quills and ravens.',
    'The greatest fools are ofttimes more clever than the men who laugh at them.',
    "It's not enough to be good. You must be great.",
    'The more you give a king, the more he wants. We are only as strong as our least powerful bannerman.',
    'Explain to me why it is more noble to kill ten thousand men in battle than a dozen at dinner.',
    'The greatest fools are ofttimes more clever than the men who laugh at them.',
    "Any man who must say 'I am the king' is no true king.",
    "A man who must say, 'I am the king,' is no true king.",
    'Wisdom oft comes from the mouths of babes.',
    'A ruler who hides behind paid executioners soon forgets what death is.',
    'The future of our family will be determined in these next few months.',
    'A lion does not concern itself with the opinion of sheep.',
    'The king is a lost cause. The country will not.',
    'The future of our family will be determined in these next few months.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'Wisdom oft comes from the mouths of babes.',
    "It's the family name that lives on. It's all that lives on.",
    'A lion does not concern himself with the opinion of sheep.',
    'A lion must not concern itself with the opinion of sheep.',
    "A lion doesn't concern itself with the opinion of sheep.",
    'Explain to me why it is more noble to kill ten thousand men in battle than a dozen at dinner.',
    'The more you give a king, the more he wants. We are only as strong as our least powerful bannerman.',
    'The king is a lost cause. The country will not.',
    'The house that puts family first will always defeat the house that puts the whims and wishes of its sons and daughters first.',
    'Some wars are won with swords and spears, others with quills and ravens.',
    'A ruler who hides behind paid executioners soon forgets what death is.',
    "It's the family name that lives on. It's all that lives on."
  ],
  varys: [
    'Power resides where men believe it resides.',
    'The storms come and go, the waves crash overhead, the big fish eat the little fish, and I keep on paddling.',
    "I've always hated the bells. They ring for horror. A dead king, a city under siege.",
    'You wish to know where my true loyalties lie? Not with any king or queen, but with the people.',
    'A wise man once said the true history of the world is a history of great conversations in elegant rooms.',
    'Influence grows like a weed.',
    'I did what I did for the good of the realm.',
    "The contents of a man's letters are more valuable than the man himself.",
    'Little birds, whispering secrets in my ear.',
    'I serve the realm, and the realm needs peace.',
    'The things I do for love.',
    "Knowledge has made you powerful, but there's still so much you don't know.",
    'What happens when we abandon the truth? It becomes a weapon.',
    'A small man can cast a very large shadow.',
    "You're quite the little hero. Fighting for the people.",
    'I believe that when you have a role to play, you should play it as well as you can.',
    "Chaos isn't a pit. Chaos is a ladder.",
    'I am a loyal servant of the realm.',
    'There is power in knowledge too, my lord.',
    'The realm is not well served by weak men.',
    'The storms come and go, the waves crash overhead, the big fish eat the little fish, and I keep on paddling.',
    'Influence grows like a weed.',
    "Knowledge has made you powerful, but there's still so much you don't know.",
    'The things I do for love.',
    'I did what I did for the good of the realm.',
    'A wise man once said the true history of the world is a history of great conversations in elegant rooms.',
    'I serve the realm, and the realm needs peace.',
    "The contents of a man's letters are more valuable than the man himself.",
    "You're quite the little hero. Fighting for the people.",
    "Chaos isn't a pit. Chaos is a ladder."
  ]
}
